# Generated by Django 3.2.5 on 2022-06-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220617_1153'),
        ('main', '0004_alter_article_author'),
    ]

    operations = [
    ]
